name: "app"

x-debug: &xdebug
  XDEBUG_CONFIG: client_host=host.docker.internal
  PHP_XDEBUG_ENABLED: 1
  XDEBUG_MODE: develop,debug,coverage
  XDEBUG_SESSION: PHPSTORM
  PHP_IDE_CONFIG: serverName=${APP_NAME}-web # Container name

services:
  web:
    image: "patrikjak/php83-laravel-development"
    container_name: "${APP_NAME}-web"
    ports:
      - "80:80"
      - "5173:5173"
      - "9003:9003" # For xdebug
    environment:
      <<: *xdebug
    volumes:
      - ".:var/www"
    networks:
      - shared
    depends_on:
      - mariadb

  cli:
    image: "patrikjak/php83-cli"
    container_name: "${APP_NAME}-cli"
    networks:
      - shared
    volumes:
      - ".:/var/www"

  mariadb:
    container_name: "database"
    image: 'mariadb:latest'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpassword'
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: '${DB_DATABASE}'
    volumes:
      - "database-data:/var/lib/mysql"
    networks:
      - shared

networks:
  shared:
    driver: bridge

volumes:
  database-data:
    driver: local